services:
  backend:
    container_name: real-home-data-backend
    image: us-docker.pkg.dev/real-data-now/gcr.io/real-home-data/backend:${GH_REF}
    build:
      context: .
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./service-account.json:/tmp/service-account.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/service-account.json
    ports:
      - 80:5000
