name: Compute Engine

on:
  push:
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  IMAGE: us-docker.pkg.dev/real-data-now/gcr.io/real-home-data/backend:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: google-github-actions/setup-gcloud@v0

      - run: gcloud auth configure-docker us-docker.pkg.dev

      - uses: satackey/action-docker-layer-caching@v0.0.11

      - run: docker build --push -t ${{ env.IMAGE }} .

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: real-home-data-backend-2
          zone: us-central1-a
          ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          user: siddhantmehandru_developer
          script: scripts/pull.sh
