name: GKE Deployment Rollout

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - master

env:
  GKE_CLUSTER: real-home-data-backend
  LOCATION: us-central1

jobs:
  rollout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.LOCATION }}

      - run: kubectl rollout restart deployments/real-home-data-backend

      - run: kubectl rollout status deployments/real-home-data-backend
